export const chartData2 = {
  qcChartByPathogenPcData: [
    {
      totalRun: 11,
      productCode: "CSTICGMTA",
      productName: "Allplex CT/NG/MG/TV Assay",
      productAbbrName: "CGMT",
      pathogenCode: "CT",
      pathogenName: "CT",
      detctRsltDvsnCode: "Ct",
      groupKey: "CT (CGMT)",
      runCount: 11,
      positiveCount: 10,
      positivePercent: 90.9,
      pathogenAllValuesArray: [
        "20.67",
        "20.71",
        "20.76",
        "20.77",
        "20.79",
        "20.79",
        "20.80",
        "20.82",
        "20.83",
        "20.93",
      ],
      average: 20.8,
      averageChart: 20.8,
      minimum: 20.67,
      minimumChart: 20.67,
      lowerQuartile: 20.8,
      median: 20.8,
      medianChart: 20.8,
      upperQuartile: 20.8,
      maximum: 20.93,
      maximumChart: 20.93,
      __typename: "qcChartData",
    },
    {
      totalRun: 11,
      productCode: "CSTICGMTA",
      productName: "Allplex CT/NG/MG/TV Assay",
      productAbbrName: "CGMT",
      pathogenCode: "MG",
      pathogenName: "MG",
      detctRsltDvsnCode: "Ct",
      groupKey: "MG (CGMT)",
      runCount: 11,
      positiveCount: 10,
      positivePercent: 90.9,
      pathogenAllValuesArray: [
        "21.53",
        "21.54",
        "21.86",
        "22.04",
        "22.13",
        "22.19",
        "22.40",
        "22.64",
        "23.01",
        "23.53",
      ],
      average: 22.3,
      averageChart: 22.3,
      minimum: 21.53,
      minimumChart: 21.53,
      lowerQuartile: 21.9,
      median: 22.2,
      medianChart: 22.2,
      upperQuartile: 22.6,
      maximum: 23.53,
      maximumChart: 23.53,
      __typename: "qcChartData",
    },
    {
      totalRun: 11,
      productCode: "CSTICGMTA",
      productName: "Allplex CT/NG/MG/TV Assay",
      productAbbrName: "CGMT",
      pathogenCode: "NG",
      pathogenName: "NG",
      detctRsltDvsnCode: "Ct",
      groupKey: "NG (CGMT)",
      runCount: 11,
      positiveCount: 11,
      positivePercent: 100,
      pathogenAllValuesArray: [
        "19.31",
        "19.78",
        "20.28",
        "21.07",
        "21.14",
        "21.18",
        "21.19",
        "21.36",
        "21.40",
        "21.45",
        "30.50",
      ],
      average: 21.7,
      averageChart: 21.7,
      minimum: 19.31,
      minimumChart: 19.31,
      lowerQuartile: 20.7,
      median: 21.2,
      medianChart: 21.2,
      upperQuartile: 21.4,
      maximum: 30.5,
      maximumChart: 30.5,
      __typename: "qcChartData",
    },
    {
      totalRun: 11,
      productCode: "CSTICGMTA",
      productName: "Allplex CT/NG/MG/TV Assay",
      productAbbrName: "CGMT",
      pathogenCode: "TV",
      pathogenName: "TV",
      detctRsltDvsnCode: "Ct",
      groupKey: "TV (CGMT)",
      runCount: 11,
      positiveCount: 10,
      positivePercent: 90.9,
      pathogenAllValuesArray: [
        "19.78",
        "20.11",
        "20.17",
        "20.83",
        "20.83",
        "20.99",
        "21.03",
        "21.06",
        "21.38",
        "21.41",
      ],
      average: 20.8,
      averageChart: 20.8,
      minimum: 19.78,
      minimumChart: 19.78,
      lowerQuartile: 20.3,
      median: 20.9,
      medianChart: 20.9,
      upperQuartile: 21.1,
      maximum: 21.41,
      maximumChart: 21.41,
      __typename: "qcChartData",
    },
    {
      totalRun: 11,
      productCode: "CSTICGMTA",
      productName: "Allplex CT/NG/MG/TV Assay",
      productAbbrName: "CGMT",
      pathogenCode: "IC",
      pathogenName: "IC",
      detctRsltDvsnCode: "Ct",
      groupKey: "IC (CGMT)",
      runCount: 11,
      positiveCount: 10,
      positivePercent: 90.9,
      pathogenAllValuesArray: [
        "19.94",
        "20.41",
        "20.60",
        "20.96",
        "21.01",
        "22.04",
        "22.12",
        "22.22",
        "22.35",
        "22.98",
      ],
      average: 21.5,
      averageChart: 21.5,
      minimum: 19.94,
      minimumChart: 19.94,
      lowerQuartile: 20.7,
      median: 21.5,
      medianChart: 21.5,
      upperQuartile: 22.2,
      maximum: 22.98,
      maximumChart: 22.98,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "16",
      pathogenName: "16",
      detctRsltDvsnCode: "Sq",
      groupKey: "16 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "18",
      pathogenName: "18",
      detctRsltDvsnCode: "Sq",
      groupKey: "18 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "31",
      pathogenName: "31",
      detctRsltDvsnCode: "Sq",
      groupKey: "31 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "33",
      pathogenName: "33",
      detctRsltDvsnCode: "Sq",
      groupKey: "33 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "35",
      pathogenName: "35",
      detctRsltDvsnCode: "Sq",
      groupKey: "35 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "39",
      pathogenName: "39",
      detctRsltDvsnCode: "Sq",
      groupKey: "39 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "45",
      pathogenName: "45",
      detctRsltDvsnCode: "Sq",
      groupKey: "45 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "51",
      pathogenName: "51",
      detctRsltDvsnCode: "Sq",
      groupKey: "51 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "52",
      pathogenName: "52",
      detctRsltDvsnCode: "Sq",
      groupKey: "52 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "56",
      pathogenName: "56",
      detctRsltDvsnCode: "Sq",
      groupKey: "56 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "58",
      pathogenName: "58",
      detctRsltDvsnCode: "Sq",
      groupKey: "58 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "59",
      pathogenName: "59",
      detctRsltDvsnCode: "Sq",
      groupKey: "59 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "66",
      pathogenName: "66",
      detctRsltDvsnCode: "Sq",
      groupKey: "66 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "68",
      pathogenName: "68",
      detctRsltDvsnCode: "Sq",
      groupKey: "68 (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28AH96F",
      productName: "AnyplexⅡ HPV28 Detection A set",
      productAbbrName: "HPVA",
      pathogenCode: "IC",
      pathogenName: "IC",
      detctRsltDvsnCode: "Sq",
      groupKey: "IC (HPVA)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "6",
      pathogenName: "6",
      detctRsltDvsnCode: "Sq",
      groupKey: "6 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "11",
      pathogenName: "11",
      detctRsltDvsnCode: "Sq",
      groupKey: "11 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "26",
      pathogenName: "26",
      detctRsltDvsnCode: "Sq",
      groupKey: "26 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "40",
      pathogenName: "40",
      detctRsltDvsnCode: "Sq",
      groupKey: "40 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "42",
      pathogenName: "42",
      detctRsltDvsnCode: "Sq",
      groupKey: "42 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "43",
      pathogenName: "43",
      detctRsltDvsnCode: "Sq",
      groupKey: "43 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "44",
      pathogenName: "44",
      detctRsltDvsnCode: "Sq",
      groupKey: "44 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "53",
      pathogenName: "53",
      detctRsltDvsnCode: "Sq",
      groupKey: "53 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "54",
      pathogenName: "54",
      detctRsltDvsnCode: "Sq",
      groupKey: "54 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "61",
      pathogenName: "61",
      detctRsltDvsnCode: "Sq",
      groupKey: "61 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "69",
      pathogenName: "69",
      detctRsltDvsnCode: "Sq",
      groupKey: "69 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "70",
      pathogenName: "70",
      detctRsltDvsnCode: "Sq",
      groupKey: "70 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "73",
      pathogenName: "73",
      detctRsltDvsnCode: "Sq",
      groupKey: "73 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "82",
      pathogenName: "82",
      detctRsltDvsnCode: "Sq",
      groupKey: "82 (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
    {
      totalRun: 15,
      productCode: "CHPV28BH96F",
      productName: "AnyplexⅡ HPV28 Detection B set",
      productAbbrName: "HPVB",
      pathogenCode: "IC",
      pathogenName: "IC",
      detctRsltDvsnCode: "Sq",
      groupKey: "IC (HPVB)",
      runCount: 4,
      positiveCount: 4,
      positivePercent: 100,
      pathogenAllValuesArray: [],
      average: 0,
      averageChart: 0,
      minimum: 0,
      minimumChart: 0,
      lowerQuartile: 0,
      median: 0,
      medianChart: 0,
      upperQuartile: 0,
      maximum: 0,
      maximumChart: 0,
      __typename: "qcChartData",
    },
  ],
};
