export const chartData3 = {
  prevalence: [
    {
      pathogenCode: "AdV",
      pathogenName: "AdV(RV-EA)",
      pathogenGroupName: "AdV",
      allPositiveCasesCount: 440,
      allPositiveCasesRate: 17.6,
    },
    {
      pathogenCode: "Flu A",
      pathogenName: "Flu A(RV-EA)",
      pathogenGroupName: "Flu A",
      allPositiveCasesCount: 422,
      allPositiveCasesRate: 16.8,
    },
    {
      pathogenCode: "Flu B",
      pathogenName: "Flu B(RV-EA)",
      pathogenGroupName: "Flu B",
      allPositiveCasesCount: 441,
      allPositiveCasesRate: 17.6,
    },
    {
      pathogenCode: "HRV",
      pathogenName: "HRV(RV-EA)",
      pathogenGroupName: "HRV",
      allPositiveCasesCount: 763,
      allPositiveCasesRate: 30.4,
    },
    {
      pathogenCode: "MPV",
      pathogenName: "MPV(RV-EA)",
      pathogenGroupName: "MPV",
      allPositiveCasesCount: 121,
      allPositiveCasesRate: 4.8,
    },
    {
      pathogenCode: "PIV",
      pathogenName: "PIV(RV-EA)",
      pathogenGroupName: "PIV",
      allPositiveCasesCount: 178,
      allPositiveCasesRate: 7.1,
    },
    {
      pathogenCode: "RSV",
      pathogenName: "RSV(RV-EA)",
      pathogenGroupName: "RSV",
      allPositiveCasesCount: 512,
      allPositiveCasesRate: 20.4,
    },
    {
      pathogenCode: "SARS-CoV-2",
      pathogenGroupData: [
        {
          pathogenCode: "E gene,N gene",
          pathogenName: "E gene,N gene(SARS-CoV-2)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 64,
          allPositiveCasesRate: 2.7,
        },
        {
          pathogenCode: "E gene,N gene,RdRP/S gene",
          pathogenName: "E gene,N gene,RdRP/S gene(SARS-CoV-2)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 1628,
          allPositiveCasesRate: 67.6,
        },
        {
          pathogenCode: "E gene,RdRP gene",
          pathogenName: "E gene,RdRP gene(2019-nCoV)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 8,
          allPositiveCasesRate: 57.1,
        },
        {
          pathogenCode: "E gene,RdRP/S gene",
          pathogenName: "E gene,RdRP/S gene(SARS-CoV-2)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 59,
          allPositiveCasesRate: 2.4,
        },
        {
          pathogenCode: "N gene",
          pathogenName: "N gene(SARS-CoV-2)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 42,
          allPositiveCasesRate: 1.7,
        },
        {
          pathogenCode: "N gene,RdRP/S gene",
          pathogenName: "N gene,RdRP/S gene(SARS-CoV-2)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 57,
          allPositiveCasesRate: 2.4,
        },
        {
          pathogenCode: "RdRP gene",
          pathogenName: "RdRP gene(2019-nCoV)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 2,
          allPositiveCasesRate: 14.3,
        },
        {
          pathogenCode: "RdRP/S gene",
          pathogenName: "RdRP/S gene(SARS-CoV-2)",
          pathogenGroupName: "SARS-CoV-2",
          allPositiveCasesCount: 61,
          allPositiveCasesRate: 2.5,
        },
      ],
      allPositiveCasesCount: 1921,
      allPositiveCasesRate: 150.7,
    },
    {
      pathogenCode: "E gene",
      pathogenName: "E gene(SARS-CoV-2 Presumptive)",
      pathogenGroupName: "SARS-CoV-2 Presumptive",
      allPositiveCasesCount: 36,
      allPositiveCasesRate: 1.5,
    },
  ],
  totalTestCases: 4930,
};
